#!/usr/bin/env python3
"""Generate docs/_generated/doc-index.md from document frontmatter.

Usage: python scripts/docmeta/generate_doc_index.py
"""

import sys
from datetime import datetime, timezone
from pathlib import Path

from frontmatter_utils import parse_frontmatter

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
OUTPUT = REPO_ROOT / "docs" / "_generated" / "doc-index.md"
GENERATED_PREFIX = "docs/_generated/"

SCAN_PATHS = [
    REPO_ROOT / "README.md",
    REPO_ROOT / "MASTERPLAN.md",
    REPO_ROOT / "AGENTS.md",
    REPO_ROOT / "docs",
]


def collect_files() -> list[Path]:
    """Collect Markdown files to index."""
    files = []
    for p in SCAN_PATHS:
        if p.is_file() and p.suffix == ".md":
            files.append(p)
        elif p.is_dir():
            for md in sorted(p.rglob("*.md")):
                rel = md.relative_to(REPO_ROOT).as_posix()
                if not rel.startswith(GENERATED_PREFIX):
                    files.append(md)
    return files


def relative_link(filepath: Path) -> str:
    """Create a relative link from docs/_generated/ to the file."""
    rel = filepath.relative_to(REPO_ROOT).as_posix()
    return f"../../{rel}"


def main():
    files = collect_files()
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    entries_with_meta = []
    entries_without_meta = []

    for filepath in files:
        rel = filepath.relative_to(REPO_ROOT).as_posix()
        meta = parse_frontmatter(filepath)
        link = relative_link(filepath)

        if meta and meta.get("id"):
            entries_with_meta.append({
                "path": rel,
                "link": link,
                "id": meta.get("id", ""),
                "title": meta.get("title", rel),
                "doc_type": meta.get("doc_type", ""),
                "status": meta.get("status", ""),
                "canonicality": meta.get("canonicality", ""),
                "summary": meta.get("summary", ""),
            })
        else:
            entries_without_meta.append(rel)

    lines = [
        "<!-- GENERATED FILE — DO NOT EDIT MANUALLY -->",
        f"<!-- Generated by scripts/docmeta/generate_doc_index.py at {now} -->",
        "",
        "# Dokumenten-Index",
        "",
        "Automatisch generierter Index aller Dokumente mit erkanntem Frontmatter.",
        "",
        "| ID | Titel | Typ | Status | Kanonizität | Pfad |",
        "|----|-------|-----|--------|-------------|------|",
    ]

    for e in sorted(entries_with_meta, key=lambda x: x["id"]):
        lines.append(
            f"| {e['id']} | {e['title']} | {e['doc_type']} | {e['status']} "
            f"| {e['canonicality']} | [{e['path']}]({e['link']}) |"
        )

    if entries_without_meta:
        lines.append("")
        lines.append("## Dokumente ohne Frontmatter")
        lines.append("")
        for path in sorted(entries_without_meta):
            lines.append(f"- `{path}`")

    lines.append("")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {OUTPUT.relative_to(REPO_ROOT)} ({len(entries_with_meta)} indexed, {len(entries_without_meta)} without frontmatter)")


if __name__ == "__main__":
    main()
