#!/usr/bin/env python3
"""Generate docs/_generated/backlinks.md showing cross-references between documents.

Usage: python scripts/docmeta/generate_backlinks.py
"""

import re
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
OUTPUT = REPO_ROOT / "docs" / "_generated" / "backlinks.md"
GENERATED_PREFIX = "docs/_generated/"

SCAN_PATHS = [
    REPO_ROOT / "README.md",
    REPO_ROOT / "MASTERPLAN.md",
    REPO_ROOT / "AGENTS.md",
    REPO_ROOT / "docs",
]

# Pattern to match Markdown links: [text](path)
LINK_PATTERN = re.compile(r"\[([^\]]*)\]\(([^)]+)\)")


def collect_files() -> list[Path]:
    """Collect Markdown files to analyze."""
    files = []
    for p in SCAN_PATHS:
        if p.is_file() and p.suffix == ".md":
            files.append(p)
        elif p.is_dir():
            for md in sorted(p.rglob("*.md")):
                rel = md.relative_to(REPO_ROOT).as_posix()
                if not rel.startswith(GENERATED_PREFIX):
                    files.append(md)
    return files


def extract_links(filepath: Path) -> list[str]:
    """Extract local Markdown links from a file, resolved to repo-relative paths."""
    text = filepath.read_text(encoding="utf-8")
    links = []
    for _label, target in LINK_PATTERN.findall(text):
        # Skip external links and anchors
        if target.startswith("http://") or target.startswith("https://") or target.startswith("#"):
            continue
        # Remove anchor fragments
        target = target.split("#")[0]
        if not target:
            continue
        # Resolve relative to file's directory
        resolved = (filepath.parent / target).resolve()
        try:
            rel = resolved.relative_to(REPO_ROOT).as_posix()
            links.append(rel)
        except ValueError:
            continue
    return links


def main():
    files = collect_files()
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    # Map: target_path -> list of source_paths that link to it
    backlinks: dict[str, list[str]] = {}

    for filepath in files:
        source = filepath.relative_to(REPO_ROOT).as_posix()
        targets = extract_links(filepath)
        for target in targets:
            if target not in backlinks:
                backlinks[target] = []
            if source not in backlinks[target]:
                backlinks[target].append(source)

    lines = [
        "<!-- GENERATED FILE — DO NOT EDIT MANUALLY -->",
        f"<!-- Generated by scripts/docmeta/generate_backlinks.py at {now} -->",
        "",
        "# Backlinks",
        "",
        "Zeigt, welche Dokumente auf welche anderen Dokumente verweisen.",
        "",
    ]

    if backlinks:
        for target in sorted(backlinks.keys()):
            sources = sorted(backlinks[target])
            lines.append(f"## `{target}`")
            lines.append("")
            lines.append("Verwiesen von:")
            for src in sources:
                lines.append(f"- `{src}`")
            lines.append("")
    else:
        lines.append("Keine Querverweise gefunden.")
        lines.append("")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {OUTPUT.relative_to(REPO_ROOT)} ({len(backlinks)} targets)")


if __name__ == "__main__":
    main()
