#!/usr/bin/env python3
"""Generate docs/_generated/system-map.md showing the repo structure overview.

Hidden paths (any path component starting with ``"."``) are excluded so that
``.git``, ``.github``, and similar infrastructure directories do not appear.

Usage: python scripts/docmeta/generate_system_map.py
"""

from datetime import datetime, timezone
from pathlib import Path

from frontmatter_utils import parse_frontmatter

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
OUTPUT = REPO_ROOT / "docs" / "_generated" / "system-map.md"


def _is_hidden(path: Path) -> bool:
    """Return True when any component of *path* starts with a dot."""
    return any(part.startswith(".") for part in path.relative_to(REPO_ROOT).parts)


def collect_tree() -> dict[str, list[str]]:
    """Build a directory tree of non-hidden files."""
    tree: dict[str, list[str]] = {}
    for item in sorted(REPO_ROOT.rglob("*")):
        if _is_hidden(item):
            continue
        rel = item.relative_to(REPO_ROOT).as_posix()
        if item.is_file():
            parent = str(item.parent.relative_to(REPO_ROOT).as_posix())
            if parent == ".":
                parent = "/"
            if parent not in tree:
                tree[parent] = []
            tree[parent].append(rel)
    return tree


def main():
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    tree = collect_tree()

    lines = [
        "<!-- GENERATED FILE — DO NOT EDIT MANUALLY -->",
        f"<!-- Generated by scripts/docmeta/generate_system_map.py at {now} -->",
        "",
        "# System-Map",
        "",
        "Strukturübersicht des Repos mit Dateitypen und Frontmatter-Status.",
        "",
    ]

    # Group by area
    areas = [
        ("/", "Root"),
        ("docs", "Dokumentation"),
        ("docs/_generated", "Generierte Artefakte"),
        ("contracts", "Contracts / Schemata"),
        ("scripts/docmeta", "Scripts / Generatoren"),
    ]

    for area_path, area_label in areas:
        files = tree.get(area_path, [])
        if not files:
            continue

        lines.append(f"## {area_label} (`{area_path}`)")
        lines.append("")

        for filepath_str in sorted(files):
            filepath = REPO_ROOT / filepath_str
            suffix = filepath.suffix

            meta_info = ""
            if suffix == ".md":
                meta = parse_frontmatter(filepath)
                if meta:
                    doc_id = meta.get("id", "?")
                    doc_type = meta.get("doc_type", "?")
                    canonicality = meta.get("canonicality", "?")
                    meta_info = f" — id:`{doc_id}` type:`{doc_type}` canon:`{canonicality}`"
                else:
                    meta_info = " — ⚠ kein Frontmatter"

            lines.append(f"- `{filepath_str}`{meta_info}")

        lines.append("")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {OUTPUT.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
