#!/usr/bin/env python3
"""Generate docs/_generated/orphans.md listing documents not linked from anywhere.

Usage: python scripts/docmeta/generate_orphans.py
"""

import re
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
OUTPUT = REPO_ROOT / "docs" / "_generated" / "orphans.md"
GENERATED_PREFIX = "docs/_generated/"

SCAN_PATHS = [
    REPO_ROOT / "README.md",
    REPO_ROOT / "MASTERPLAN.md",
    REPO_ROOT / "AGENTS.md",
    REPO_ROOT / "docs",
]

LINK_PATTERN = re.compile(r"\[([^\]]*)\]\(([^)]+)\)")

# Files that are structural entry points and never orphans
ENTRY_POINTS = {"README.md", "MASTERPLAN.md", "AGENTS.md"}


def collect_files() -> list[Path]:
    """Collect Markdown files."""
    files = []
    for p in SCAN_PATHS:
        if p.is_file() and p.suffix == ".md":
            files.append(p)
        elif p.is_dir():
            for md in sorted(p.rglob("*.md")):
                rel = md.relative_to(REPO_ROOT).as_posix()
                if not rel.startswith(GENERATED_PREFIX):
                    files.append(md)
    return files


def extract_link_targets(filepath: Path) -> set[str]:
    """Extract resolved local link targets from a file."""
    text = filepath.read_text(encoding="utf-8")
    targets = set()
    for _label, target in LINK_PATTERN.findall(text):
        if target.startswith("http://") or target.startswith("https://") or target.startswith("#"):
            continue
        target = target.split("#")[0]
        if not target:
            continue
        resolved = (filepath.parent / target).resolve()
        try:
            rel = resolved.relative_to(REPO_ROOT).as_posix()
            targets.add(rel)
        except ValueError:
            continue
    return targets


def main():
    files = collect_files()
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    # Collect all files and all link targets
    all_files = set()
    all_targets = set()

    for filepath in files:
        rel = filepath.relative_to(REPO_ROOT).as_posix()
        all_files.add(rel)
        targets = extract_link_targets(filepath)
        all_targets.update(targets)

    # Orphans: files that exist but are not linked to from anywhere,
    # excluding entry points
    orphans = sorted(all_files - all_targets - ENTRY_POINTS)

    lines = [
        "<!-- GENERATED FILE — DO NOT EDIT MANUALLY -->",
        f"<!-- Generated by scripts/docmeta/generate_orphans.py at {now} -->",
        "",
        "# Verwaiste Dokumente (Orphans)",
        "",
        "Dokumente, die von keinem anderen Dokument im Repo verlinkt werden.",
        "Einstiegspunkte (README.md, MASTERPLAN.md, AGENTS.md) sind ausgenommen.",
        "",
    ]

    if orphans:
        lines.append(f"**{len(orphans)} verwaiste(s) Dokument(e) gefunden:**")
        lines.append("")
        for orphan in orphans:
            lines.append(f"- `{orphan}`")
        lines.append("")
        lines.append("> Diese Dokumente sollten entweder verlinkt oder bewusst als eigenständig markiert werden.")
    else:
        lines.append("Keine verwaisten Dokumente gefunden. Alle Dokumente sind verlinkt.")

    lines.append("")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {OUTPUT.relative_to(REPO_ROOT)} ({len(orphans)} orphans)")


if __name__ == "__main__":
    main()
